<?php
require('C:\xampp\htdocs\library\fpdf\fpdf.php');
include 'config.php';

class EnhancedPenaltyReportPDF extends FPDF {
    private $primaryColor;
    private $secondaryColor;
    private $accentColor;
    private $neutralColors;

    public function __construct() {
        parent::__construct();
        // Refined color palette
        $this->primaryColor = [31, 97, 141];    // Deep Blue
        $this->secondaryColor = [52, 152, 219]; // Bright Blue
        $this->accentColor = [231, 76, 60];     // Soft Red
        $this->neutralColors = [
            'dark' => [44, 62, 80],     // Dark Slate Blue
            'light' => [236, 240, 241], // Very Light Gray
            'medium' => [189, 195, 199] // Medium Gray
        ];
    }

    function Header() {
        // Watermark background
        $this->SetDrawColor($this->neutralColors['medium'][0], 
                            $this->neutralColors['medium'][1], 
                            $this->neutralColors['medium'][2]);
        $this->SetLineWidth(0.1);
        for ($i = 0; $i < $this->w; $i += 20) {
            $this->Line($i, 0, $i, $this->h);
            $this->Line(0, $i, $this->w, $i);
        }
        
        // Logo
        $this->Image('Logo/tupi.png', 15, 5, 30);
        
        // School information
        $this->SetFont('Arial', '', 10);
        $this->SetTextColor($this->neutralColors['dark'][0], 
                            $this->neutralColors['dark'][1], 
                            $this->neutralColors['dark'][2]);
        $this->SetXY(120, 20);
        $this->Cell(80, 5, 'Tupi National High School', 0, 1, 'R');
        $this->SetX(120);
        $this->Cell(80, 5, 'Purok 11, Poblacion, Tupi, South Cotabato', 0, 1, 'R');
        $this->SetX(120);
        $this->Cell(80, 5, 'Phone: (123) 456-7890', 0, 1, 'R');
        
        // Decorative line
        $this->SetDrawColor($this->primaryColor[0], 
                            $this->primaryColor[1], 
                            $this->primaryColor[2]);
        $this->SetLineWidth(0.5);
        $this->Line(10, 40, $this->w - 10, 40);
        
        // Report Title
        $this->Ln(20);
        $this->SetFont('Arial', 'B', 28);
        $this->SetTextColor($this->primaryColor[0], 
                            $this->primaryColor[1], 
                            $this->primaryColor[2]);
        $this->Cell(0, 15, 'PENALTY REPORT', 0, 1, 'C');
        
        // Report metadata
        $this->SetFont('Arial', '', 10);
        $this->SetTextColor($this->neutralColors['dark'][0], 
                            $this->neutralColors['dark'][1], 
                            $this->neutralColors['dark'][2]);
        $this->Cell(0, 8, 'Report Date: ' . date('Y-m-d') . ' | Generated By: Staff', 0, 1, 'C');
        
        $this->Ln(10);
    }
    
    function Footer() {
        $this->SetY(-30);
        $this->SetFont('Arial', '', 8);
        $this->SetTextColor($this->neutralColors['dark'][0], 
                            $this->neutralColors['dark'][1], 
                            $this->neutralColors['dark'][2]);
        
        // Page number
        $this->Cell(0, 10, 'Page ' . $this->PageNo() . ' of {nb}', 0, 1, 'C');
        
        // Footer notes
        $this->SetFont('Arial', '', 7);
        $this->MultiCell(0, 4, 
            "1. All penalties must be paid within 30 days of issuance\n" .
            "2. This is a computer-generated document\n" . 
            "3. For questions, contact the library staff", 
            0, 'C'
        );
    }

    function PrintTableHeader($headers) {
        $this->SetFont('Arial', 'B', 10);
        // Use primary color for header background
        $this->SetFillColor($this->primaryColor[0], 
                            $this->primaryColor[1], 
                            $this->primaryColor[2]);
        $this->SetTextColor(255, 255, 255); // White text
        
        foreach ($headers as $header) {
            $this->Cell($header['width'], 10, $header['name'], 1, 0, $header['align'], true);
        }
        $this->Ln();
    }

    function PrintPenaltyTable($query, $conn) {
        $result = $conn->query($query);
        
        $headers = [
            ['name' => 'ID', 'width' => 20, 'align' => 'L'],
            ['name' => 'Student Name', 'width' => 50, 'align' => 'L'],
            ['name' => 'Book Title', 'width' => 50, 'align' => 'L'],
            ['name' => 'Due Date', 'width' => 25, 'align' => 'L'],
            ['name' => 'Penalty Fee', 'width' => 25, 'align' => 'R'],
            ['name' => 'Status', 'width' => 20, 'align' => 'C']
        ];

        $this->PrintTableHeader($headers);
        $this->SetFont('Arial', '', 9);
        $fill = false;
        $total = 0;

        while ($row = $result->fetch_assoc()) {
            // Alternating row colors with subtle gray tones
            $this->SetFillColor($fill ? $this->neutralColors['light'][0] : 255, 
                                $fill ? $this->neutralColors['light'][1] : 255, 
                                $fill ? $this->neutralColors['light'][2] : 255);
            
            // Text color for rows
            $this->SetTextColor($this->neutralColors['dark'][0], 
                                $this->neutralColors['dark'][1], 
                                $this->neutralColors['dark'][2]);

            $this->Cell(20, 8, $row['penalty_id'], 1, 0, 'L', true);
            $this->Cell(50, 8, $row['student_name'], 1, 0, 'L', true);
            $this->Cell(50, 8, $row['book_title'], 1, 0, 'L', true);
            $this->Cell(25, 8, date('Y-m-d', strtotime($row['due_date'])), 1, 0, 'L', true);
            
            // Use accent color for penalty amount
            $this->SetTextColor($this->accentColor[0], 
                                $this->accentColor[1], 
                                $this->accentColor[2]);
            $this->Cell(25, 8, 'PHP ' . number_format($row['total_penalty_fee'] ?? $row['penalty_fee'], 2), 1, 0, 'R', true);
            
            // Status color
            $this->SetTextColor($this->neutralColors['dark'][0], 
                                $this->neutralColors['dark'][1], 
                                $this->neutralColors['dark'][2]);
            $this->Cell(20, 8, $row['status'] == 'unpaid' ? 'Unpaid' : 'Paid', 1, 1, 'C', true);
            
            $fill = !$fill;
            $total += $row['total_penalty_fee'] ?? $row['penalty_fee'];
        }

        return $total;
    }
}

// Rest of the code remains the same as in the previous example
$pdf = new EnhancedPenaltyReportPDF();
$pdf->AliasNbPages();
$pdf->AddPage();
$pdf->SetMargins(10, 10, 10);


// Create PDF instance
$pdf = new EnhancedPenaltyReportPDF();
$pdf->AliasNbPages(); // Enable total page number tracking
$pdf->AddPage();
$pdf->SetMargins(10, 10, 10);

// Unpaid Penalties Section
$pdf->SetFont('Arial', 'B', 14);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(0, 10, 'Unpaid Penalties', 0, 1, 'L');

$unpaid_query = "
    SELECT p.penalty_id,
            CONCAT(s.first_name, ' ', s.last_name) AS student_name,
            b.title AS book_title,
            t.due_date,
            GREATEST(p.penalty_fee, p.penalty_fee + (DATEDIFF(CURRENT_DATE, t.due_date) * 20)) as total_penalty_fee,
            p.status
    FROM penalties p
    JOIN borrowingtransactions t ON p.transaction_id = t.transaction_id
    JOIN students s ON t.borrower_id = s.student_id
    JOIN books b ON t.book_id = b.book_id
    WHERE p.status = 'unpaid'
    ORDER BY p.penalty_id DESC";

$total_unpaid = $pdf->PrintPenaltyTable($unpaid_query, $conn);

// Paid Penalties Section
$pdf->Ln(15);
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Paid Penalties', 0, 1, 'L');

$paid_query = "
    SELECT p.penalty_id,
            CONCAT(s.first_name, ' ', s.last_name) AS student_name,
            b.title AS book_title,
            t.due_date,
            p.penalty_fee,
            p.status
    FROM penalties p
    JOIN borrowingtransactions t ON p.transaction_id = t.transaction_id
    JOIN students s ON t.borrower_id = s.student_id
    JOIN books b ON t.book_id = b.book_id
    WHERE p.status = 'paid'
    ORDER BY p.payment_date DESC";

$total_paid = $pdf->PrintPenaltyTable($paid_query, $conn);

// Totals Summary with enhanced design
$pdf->Ln(10);
$pdf->SetFillColor(255, 255, 255);
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(145, 12, 'Total Unpaid Penalties:', 1, 0, 'R', true);
$pdf->Cell(45, 12, 'PHP ' . number_format($total_unpaid, 2), 1, 1, 'R', true);

$pdf->Cell(145, 12, 'Total Paid Penalties:', 1, 0, 'R', true);
$pdf->Cell(45, 12, 'PHP ' . number_format($total_paid, 2), 1, 1, 'R', true);

$pdf->SetFillColor(180, 180, 180);
$pdf->Cell(145, 12, 'GRAND TOTAL:', 1, 0, 'R', true);
$pdf->Cell(45, 12, 'PHP ' . number_format($total_paid + $total_unpaid, 2), 1, 1, 'R', true);

$pdf->Output('I', 'Penalty_Report.pdf');
?>